image:
  - Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - gradle wrapper --gradle-version 6.0
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - gradle --version